### ISSUE TITLE
Sliding and ball-cushion issue?

### ISSUE THREAD

**Issue by Magic73** [ekiefl/pooltool#39] opened 2022-10-19 21:02 UTC
Hello,
I made a 3d billiard game (without jump), and days ago I came across your blog which I read with great interest.
In my game I used physics calculated in discrete times, and your approach to events intrigued me. I've seen what you've done and it seems like a great job, and I've done some testing and I wanted to compare your work with what I have done, in terms of results

I read the blog and looked at the code, and did several test runs to see the results.
At first glance it seemed like a good simulation, but there was something wrong with the rotation of the ball, and also I think that the ball slide too much.

Here the setup (gen_dataset.py):
    
```
    table = pt.BilliardTable(model_name='7_foot')
    cueball = pt.Ball('cue')
    cueball.rvw[0] = [0.5, 0.25, cueball.R]
    balls = {
            'cue': cueball,
        }

    cue = pt.Cue(cueing_ball=balls['cue'])

    cue.aim_at_pos([1, 0.5, 0])
    cue.strike(V0=5, theta=10, a=0, b=0)
```

Here a video: https://youtu.be/NZbXrBUPQPw
(reduce the YT video speed at 0.25x)
after the ball hits the cushion, it assumes a completely wrong rotation, both visually and looking at the angular velocity line.

Here a video about the sliding (with the default sliding friction u_s=0.2): https://youtu.be/z6J_Yj0ap5M
look at the sliding after the ball->cushion collision. the ball slides very much every time. 

and the same shot, but with sliding friction  u_s = 1 : https://youtu.be/0gLN_UfJgz0
with this value, the sliding is reduced. the final result is near to what it should look like.

is there some errors on the physics, or the correct sliding friction u_s parameter should be higher than the default one?

Increasing the sliding friction, seems to fix the wrong rotation of the first video. with a value of 2.5, seems good.

**Comment by Magic73** [comment] 2022-10-20 05:17
are you absolutely sure of this?  https://ekiefl.github.io/images/pooltool/pooltool-theory/ball_cushion_inhwan_han.pdf

**Comment by ekiefl** [comment] 2022-10-20 07:13
>Hello,
I made a 3d billiard game (without jump), and days ago I came across your blog which I read with great interest.
In my game I used physics calculated in discrete times, and your approach to events intrigued me. I've seen what you've done and it seems like a great job, and I've done some testing and I wanted to compare your work with what I have done, in terms of results

That's really cool our interests align! And thanks for your praise. Is your project public? I would love to take a look.

> Here a video: https://youtu.be/NZbXrBUPQPw
(reduce the YT video speed at 0.25x)

I looked at your video earlier today. At first glance it was very worrying, as if the ball was sliding around more than it should. But then I realized the initial ball speed **very** high. Do you realize how fast this shot is?

For context, I reproduced your shot on the master branch with the following script:

_(It seems you turned off ball-pocket collisions, but I didn't)_

```python
#! /usr/bin/env python

import pooltool as pt

interface = pt.ShotViewer()

table = pt.PocketTable(model_name='7_foot')
cueball = pt.Ball('cue')
cueball.rvw[0] = [0.5, 0.25, cueball.R]
balls = {
    'cue': cueball,
}

cue = pt.Cue(cueing_ball=balls['cue'])

cue.aim_at_pos([1, 0.5, 0])
cue.strike(V0=5, theta=10, a=0, b=0)

shot = pt.System(cue=cue, table=table, balls=balls)
shot.simulate(continuize=True)

print(shot.events)

interface.show(shot)
```

This prints out the following event list:

```
0: <NonEvent object at 0x13cc4ddc0>
 ├── time   : 0
 └── agents : []

1: <BallCushionCollision object at 0x13cc1f9a0>
 ├── time   : 0.05899588921717758
 └── agents : ['cue', '15_edge']

2: <BallPocketCollision object at 0x13cdee880>
 ├── time   : 0.24097057919723164
 └── agents : ['cue', 'lc']

3: <NonEvent object at 0x13ce1e280>
 ├── time   : 0.24097057919823164
 └── agents : []
```

Only 200ms pass between the time of the ball-cushion collision and the ball-pocket collision. On my screen the shot repeats 4 times a second. This is basically unrealistically fast, and keep in mind the **Han model is just a simple model**.

> after the ball hits the cushion, it assumes a completely wrong rotation, both visually and **looking at the angular velocity line**

This is my fault, but that angular velocity vector is wrong. The problem is that the line drawn "pinned" to the ball, so it precesses (like a spinning top) in instances where it should remain uni-directional.

> Here a video about the sliding (with the default sliding friction u_s=0.2): https://youtu.be/z6J_Yj0ap5M
look at the sliding after the ball->cushion collision. the ball slides very much every time.

This isn't very illustrative, because I don't know how much you've slowed the video down. If it's a fast shot it will slide more. If it's a slow shot it will slide less.

> is there some errors on the physics, or the correct sliding friction u_s parameter should be higher than the default one?

I took close to the average value found here: https://billiards.colostate.edu/faq/physics/physical-properties/. You're welcome to pick whatever value you want. I don't think there are errors in the equations, or in the code that implements them.

> Increasing the sliding friction, seems to fix the wrong rotation of the first video. with a value of 2.5, seems good.

Feel free to experiment. I have found the Han model to be quite different from reality. I hope I conveyed this well enough in the blog post. You're probably giving it too much credit.

> are you absolutely sure of this? https://ekiefl.github.io/images/pooltool/pooltool-theory/ball_cushion_inhwan_han.pdf

There are not many things I would say I am absolutely sure of.

> Also, I tried to reproduce the Venom's massè shot, and the final result is different from the one that you plotted.
>
> Before:
> https://ekiefl.github.io/images/pooltool/pooltool-start/comparison.gif
>
>Now:
>https://youtu.be/xVs6Chtd4SQ

Couple of things. (1) That shot is using a discrete time simulator, not the event based. (2) Are you sure the table parameters are shared between the two simulations?

Unless we find good reason to doubt the legitimacy of the current simulation, I don't think there are any actions to take. Comparing the current state to the massé trajectory, which was generated with a different shot evolution algorithm, under potentially different cloth/ball/stick parameters, when the project was only 1 month old, is not convincing evidence.

**Comment by Magic73** [comment] 2022-10-20 09:21
Hi @ekiefl ,
the power of shot is set to 5m/s, isn't it?
Accordingly to this table, should be a powerful shot, but still realistic.
https://billiards.colostate.edu/faq/speed/typical/

this guy with a 9-railshot, has covered 4 times the length of the table. : https://youtu.be/z-D5jTm7dtE?t=23


For the table, I used BilliardTable (without changing the model :P )

About this video: https://www.youtube.com/watch?v=z6J_Yj0ap5M

It's a 4 rail shots. look at 0:05s, the ball hit the rail for the second time after going twice the length of the table  and after the ball_cushion, the ball starts to slide again for 30% of the table, and the same on the next cushion hit.

Just to avoid misunderstandings, I'm not making any criticisms of your excellent work, I'm just trying to figure out whether or not there is a problem somewhere, because there is something wrong with me in what I see.

I just wanted to compare your physics to what I did :)
because the approach to events you used seems to me a great choice.

**Comment by Magic73** [comment] 2022-10-20 17:02
Hi @ekiefl 
I found an issue :) with the collision.
the problem is caused by rounding, which inevitably leads to a greater or lesser error. Obviously, the higher speed accentuates the problem.

to calculate a collision, you determine the time.
time, which is however an approximate value. it cannot be exact 99% of the time.
when the ball is made to move, and reaches the expected point of collision, the error occurs .. over or under.

the ball will never be at a distance equal to its radius from the expected point of impact, it will be a little earlier or a little later depending on the inevitable rounding due to the finite (albeit large) precision of the double-precision numbers.

quindi, i calcoli successivi si baseranno su un punto d'impatto diverso da quello previsto, con tutte le conseguenze del caso.

Look:

![image](https://user-images.githubusercontent.com/7645382/197012482-b365ed33-f11a-49aa-b838-58372f0e077d.png)

the ball has entered the rail.

the higher the speed of the ball, the greater the error can be.

what should be added is the correction of the position of the ball, which visually will be imperceptible, but from a physical point of view, will make the subsequent calculation more precise.
and this applies to every collision.

**Comment by Magic73** [comment] 2022-10-21 06:19
I found another error, this time inside continuize.

       ```
         step = 0
                while step < dtau_E:
                    rvw, s = physics.evolve_ball_motion(
                        state=s,
                        rvw=rvw,
                        R=ball.R,
                        m=ball.m,
                        u_s=ball.u_s,
                        u_sp=ball.u_sp,
                        u_r=ball.u_r,
                        g=ball.g,
                        t=dt,
                    )
```

the error is on the while condition. step is the current time, but if the sum of current time and the dt is greater of the dtau_E limit, the ball is evolved more than necessary, and at the end of the while, the reminder part is calculated with a negative dt.

this error would create wrong playback. but unfortunatly, this doesn't fix yet the wrong rotation. :(

the correct while condition should be:

 ```
while (step + dt) < dtau_E:
                    rvw, s = physics.evolve_ball_motion(
                        state=s,
                        rvw=rvw,
                        R=ball.R,
                        m=ball.m,
                        u_s=ball.u_s,
                        u_sp=ball.u_sp,
                        u_r=ball.u_r,
                        g=ball.g,
                        t=dt,
                    )
```

**Comment by ekiefl** [comment] 2022-10-21 07:43
> Hi @ekiefl ,
the power of shot is set to 5m/s, isn't it?
Accordingly to this table, should be a powerful shot, but still realistic.
https://billiards.colostate.edu/faq/speed/typical/

That is the speed of the cue stick. Cue ball is going 8.8m/s:

```python
#! /usr/bin/env python

import numpy as np
import pooltool as pt

interface = pt.ShotViewer()

table = pt.PocketTable(model_name='7_foot')
cueball = pt.Ball('cue')
cueball.rvw[0] = [0.5, 0.25, cueball.R]
balls = {
    'cue': cueball,
}

cue = pt.Cue(cueing_ball=balls['cue'])

cue.aim_at_pos([1, 0.5, 0])
cue.strike(V0=5, theta=10, a=0, b=0)

shot = pt.System(cue=cue, table=table, balls=balls)
shot.simulate(continuize=True)

print(np.linalg.norm(shot.balls['cue'].history.rvw[0][1]))
```

Regardless, you're completely right. It is a realistic speed. But I think we _both_ agree that Hans is not a realistic model. I don't think you will find an error in my code that suddenly makes the physics look realistic, because the underlying model is bad.

> It's a 4 rail shots. look at 0:05s, the ball hit the rail for the second time after going twice the length of the table and after the ball_cushion, the ball starts to slide again for 30% of the table, and the same on the next cushion hit.

Yes, I agree. That seems unrealistic. I have not invested any time into finding the magic numbers that best emulate reality.

**Comment by ekiefl** [comment] 2022-10-21 07:45
> Hi @ekiefl
I found an issue :) with the collisions.
the problem is caused by rounding, which inevitably leads to a greater or lesser error. Obviously, the higher speed accentuates the problem.

Very nice detective work. I will add these corrections all collisions when I find time. But the error introduced by floating point precision is very, very, very, very, very, very small. Observe:

```python
#! /usr/bin/env python

import pooltool as pt
import numpy as np

table = pt.PocketTable(model_name='7_foot')
cueball = pt.Ball('cue')
cueball.rvw[0] = [0.5, 0.25, cueball.R]
balls = {
    'cue': cueball,
}

cue = pt.Cue(cueing_ball=balls['cue'])
system = pt.System(cue=cue, table=table, balls=balls)

for v0 in [1, 10, 100, 1000]:
    shot = system.copy()

    shot.cue.aim_at_pos([0.5, 0.0, shot.balls['cue'].R])
    shot.cue.strike(V0=v0, theta=0, a=0, b=0)
    shot.simulate(continuize=False, quiet=True)

    collision = shot.events[1]
    rvw = shot.events[1].agent1_state_initial[0]
    y = rvw[0][1]

    ball_speed = np.linalg.norm(shot.balls['cue'].history.rvw[0][1])
    error = abs(y - shot.balls['cue'].R)

    print(f"Ball speed {ball_speed:.2f}m/s yields error of {error}m")
```

Here I am shooting the cue ball into the bottom cushion with cue stick speeds 1m/s, 10m/s, 100m/s and 1000m/s. For each I print out the discrepancy between the ball's position and the cushion. This results in

```
Ball speed 1.75m/s yields error of 3.8163916471489756e-17m
Ball speed 17.54m/s yields error of 1.4228201949961772e-14m
Ball speed 175.44m/s yields error of 5.650098444665019e-13m
Ball speed 1754.42m/s yields error of 1.2716204131346664e-10m
```

Even at 17m/s the error you describe is 14 femtometers. This is the size of a carbon nuclei.

**Comment by Magic73** [comment] 2022-10-21 07:46
continuize, another small issue:

```
                while (step + dt) < dtau_E:
                    rvw, s = physics.evolve_ball_motion(
                        state=s,
                        rvw=rvw,
                        R=ball.R,
                        m=ball.m,
                        u_s=ball.u_s,
                        u_sp=ball.u_sp,
                        u_r=ball.u_r,
                        g=ball.g,
                        t=dt,
                    )

                    cts_history.add(rvw, s, curr_event.time + step)
                    step += dt
```

the correct time for the item in the history, should be curr_event.time + step + DT.

so the instructions should be inverted.

```
                    step += dt
                    cts_history.add(rvw, s, curr_event.time + step)

```

**Comment by ekiefl** [comment] 2022-10-21 07:47
> I found another error, this time inside continuize.

I'll look into this when I find time. Thank you very much.

**Comment by Magic73** [comment] 2022-10-21 07:48
> Even at 17m/s the error you describe is 14 femtometers. This is the size of a carbon nuclei.

yes, I saw.. but the error will spread to each event, becoming more and more consistent and heavy.

**Comment by Magic73** [comment] 2022-10-21 07:58
please, check the angular velocity error.

**Comment by ekiefl** [comment] 2022-10-21 08:01
> There are how many events in a pool simulation? 100? You're lacking perspective if you believe this is a big issue.

Sorry. This was rude. To be clear, thanks for discovering this. I am keen to implement this because I have noticed that every once in a while, balls will fully intersect with each other, and collide with their internal surfaces, if that makes any sense. These floating point errors are likely the cause.

**Comment by Magic73** [comment] 2022-10-21 08:15
> > There are how many events in a pool simulation? 100? You're lacking perspective if you believe this is a big issue.
> 
> Sorry. This was rude. To be clear, thanks for discovering this. I am keen to implement this because I have noticed that every once in a while, balls will fully intersect with each other, and collide with their internal surfaces, if that makes any sense. These floating point errors are likely the cause.

don't worry about :)

but yes, the errors caused by rounding over time add up, and lead to unexpected results.

**Comment by Magic73** [comment] 2022-10-21 12:13
at the end I think I found the error in the ball-cushion collision.

if the formulas are not wrong, the input data is wrong. and among the input data, there are those relating to the cushion.

Normal and LXY0

Inside linear cushion segment:
```
            if (p2.X - p1.X == 0)
            {
                this.lxy0 = new Vector3D(1, 0, -p1.X);
            }
            else
            {
                this.lxy0 = new Vector3D(-(p2.Y - p1.Y) / (p2.X - p1.X), 1, (p2.Y - p1.Y) / (p2.X - p1.X) * p1.X - p1.Y);
            }
```

the true case, I think is wrong. I'm quite sure.. I've to check "pratically".

https://ekiefl.github.io/2020/12/20/pooltool-alg/#-ball-ball-collision

you are solving the equation y=mx+b, but in case of p2.X = p1.X I don't understand what you did, but I think that in this case, you have to solve the equation x = (y - b) / m and then build the lxy0 vector.

in the billiard table, 2 cushion have the wrong normal, pointing outside the table.

**Comment by Magic73** [comment] 2022-10-21 12:27
The straight line through two points will have an equation in the form: y = mx + q

m = (y2 - y1) / (x2 - x1)

q = (x2 * y1 - x1 * y2) / (x2 - x1)

but this isn't the solution written in your blog:

m = (y2 - y1) / (x2 - x1)

q = y1 - ((y2 - y1) / (x2 -x1)) * x1


am I wrong something?

**Comment by ekiefl** [comment] 2022-10-22 01:38
This thread has become a whirlwind of disorganization. I'm closing this issue. Please organize any further findings into separate issues.

If the normals pointed in opposite directions, why would the ball reflect off the rail? I'm not saying you're wrong, but if you truly think there is something wrong with the normals, open a new issue. And _please_ provide a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.).

If you don't know how to write a minimum reproducible example, see any of the code I've posted above.

**Closed by ekiefl** 2022-10-22 01:38 UTC

**Comment by Magic73** [comment] 2022-10-22 06:04
ok, but normals should be:
0 1
0 -1
1 0
-1 0

**Comment by ekiefl** [comment] 2022-10-22 07:32
> ok, but normals should be:
> 0 1
> 0 -1
> 1 0
> -1 0

This is exactly what I'm talking about. This is meaningless. Give me an example. A script. Something that runs start to finish. Maybe it illustrates an error, or maybe it compares the approach you're suggesting to the approach currently implemented.

**Comment by Magic73** [comment] 2022-10-25 06:55
Maybe I found where is the error.

From the Han's paper:
that the reference frame changes from ball-centric to cushion centric, with an Y-axis tangential and an x-axis perpendicular to the cushion. 

![image](https://user-images.githubusercontent.com/7645382/197702384-4b578b28-186a-4da7-9920-32b844214206.png)

Instead you just rotate around Z:

![image](https://user-images.githubusercontent.com/7645382/197703402-9d499746-0bc1-468d-8b87-0fad2c324148.png)

**Comment by ekiefl** [comment] 2022-10-25 15:03
> the correct rotation should be around y axis by 90° + theta (clockwise, with y up).

How you've managed to butcher the coordinates that badly, I will never understand. All that's required "to have the Y-axis tangential and an X-axis perpendicular to the cushion", is to rotate about the Z-axis. Z-axis is parallel with the normal and with gravity, not in the playing surface plane lol.

> BTW, another guy used the Han's equations without changing them (so, it seems that there isn't any error inside)

Math doesn't lie.

-----------------

You are losing credibility fast.

**Comment by Magic73** [comment] 2022-10-25 15:36
I don't understand why you have to relate in this way .. think, I'm wasting time trying to understand why your project returns a completely wrong rotation when it hits a cushion.

I don't understand why you can't see it. The Z axis "MUST" pass through the center of the ball.

maybe this way you understand it better :
![image](https://user-images.githubusercontent.com/7645382/197816918-8c28702d-af29-4cd3-94d5-ac391e2476c2.png)

Math don't lie, true. but your assumption is wrong. 
but I'm not going to be here arguing.

If this is correct for you, maybe the mistake is what I see when I play pool :)

https://youtu.be/NZbXrBUPQPw

**Comment by Magic73** [comment] 2022-10-25 15:51
From your notes:
"_So he basically has the correct final form, but the wrong intermediates. The problem is that I need the intermediates to solve for the angular velocity evolution (only the linear velocities are explictly stated)._"

Too bad, however, that starting from the latter of which you confirm its correctness, and going back through the steps, we arrive at the same intermediate equations, which are therefore correct, and since you are using the wrong rotation, it would not surprise me that your assumption is also wrong.

I invite you to read this thesis, in which the same equations of Han have been used, and without the need for any modification.
(https://essay.utwente.nl/59134/1/scriptie_J_van_Balen.pdf)

maybe you're right, and we're all stupid.

**Comment by ekiefl** [comment] 2022-10-26 03:16
> Too bad, however, that starting from the latter of which you confirm its correctness, and going back through the steps, we arrive at the same intermediate equations, which are therefore correct, and since you are using the wrong rotation, it would not surprise me that your assumption is also wrong.

I have an algebraic exercise for you.

From the paper:

_"Substituting the expressions for impulses from Eq. (21) or (22) into Eq. (23), the post-impact velocities of the ball are obtained as Eq. (24) and (25)."_

As recommended, please substitute Eq 21a into Eq 23a. You should of course get Eq 24a:

$$
v_{X}' = v_{X0}  - v_{X0} ( \frac{2}{7} \sin^2 \theta_a + (1+e) \cos^2 \theta_a) - \frac{2}{7} R \omega_{Y0} \sin \theta_a
$$

But if you did your algebra correctly, that's not what you get, is it? You get

$$
v_{X}' = v_{X0}  - v_{X0} ( \frac{2}{7} \sin^2 \theta_a - (1+e) \sin \theta_a \cos \theta_a) - \frac{2}{7} R \omega_{Y0} \sin \theta_a
$$

That of course means that the intermediate equations were transcribed incorrectly, or the final result was transcribed incorrectly. I assume the latter is not the case.

Now make my modifications to Eq. (14c) and (21a) and try again. If you did your algebra right, you will get Eq. (24a). These modifications also yield the correct forms for Eqs. (24a), (24b), (25a) and (25b).

To be clear, my modifications do not alter the the final equations (Eq. (24) and Eq. (25)), they correct the intermediate mathematical equations. For whatever reason, when the paper was written these intermediate equations contained some typos. It happens all the time in academia, especially in low tier journals like _Journal of Mechanical Science and Technology_ (impact factor 1.7). Getting thorough reviewers who catch these mistakes is unlikely. I don't think it's anyone's fault.

> I invite you to read this thesis, in which the same equations of Han have been used, and without the need for any modification (page 23, so you don't even have to search).
(https://essay.utwente.nl/59134/1/scriptie_J_van_Balen.pdf)

I am very familiar with this work. I don't know if J van Balen modified any of the equations or not. And neither do you unless you have access to his code.

Please consider the following quotes:

_"Contra-spin on the first cushion reacts very different in real life, when compared to the simulated shots. **This indicates a flaw in the model**. This was the cause for failure in 23 of the 46 not reproducible solutions."_ - page 37

_"As expected, because shots with contra-effect are **not simulated accurately**, solutions having contra-effect are impossible to carry out on a real table. **This was confirmed by the expert in all cases**."_ - page 40

_"The requirement that solutions that are generated should be accurate, i.e. reproducible by a user on a real table, is fairly met. This is shown by the evaluation in paragraph 4.1.4.2. **The biggest violation of this requirement was caused by solutions requiring contra-spin on the first cushion**. Therefore it is decided that these type of solutions will be ignored. Although these type of shots sometimes are feasible solutions, it does not occur very frequent. Another problem concerning reproducibility was that the prediction of kisses sometimes failed. This can be attributed to **inaccuracies in the physical model**."_ - page 45

A model can be implemented without error, and yet still be physically inaccurate. I'm unconvinced you understand that.

> maybe you're right, and we're all stupid.

I don't think that J van Balen is stupid, because he clearly understands the limitations of Han's model. He ignored contra-spin effects and only considered shots <4m/s. 

On the other hand, the shot you're obsessed with involves contra-spin and has an initial speed of 8.8m/s.

**Comment by Magic73** [comment] 2022-11-06 13:14
And in the end I corrected the mistakes you made, and as you can see now the movement is correct (and always with the same shot, which you arbitrarily and mistakenly judge too strong :)).

I could tell you the mistakes you made, and why. But unfortunately you have proved to be an arrogant, presumptuous person and you have also taken the liberty of insulting me several times.

I don't think it will be easy for you to find mistakes, because it would mean looking at your work with self-criticism, which you have amply demonstrated that you cannot do, despite the evidence that something was not quite right.

Thanks anyway for the work done, because it gave me the opportunity to learn an event-based solution that I did not know before. I probably know your code better now than you do :)

Ah, don't be sure if you understand 100% what you have read from the theoretical documentation (Leckie, Greenspan, Han ...)

Have a good day.

https://youtu.be/i6NVgqK42wg

**Comment by ekiefl** [comment] 2022-11-06 21:04
Thanks for all your hard work! I also know how to turn up the sliding friction on my tool, but I'm glad you prefer the way the animation looks when you do that.

Since there is no further issue here, and since your posts have turned malicious, I'm deleting this thread. I'll give you one day's time to archive whatever information you may want.

Please feel free to continue using pooltool in whatever capacity you like. Perhaps you could even repurpose the code and rebrand it as _pooltool-fixed_ or _better-pooltool_. However, since you've firmly expressed your disinterest in open collaboration, I see no reason to allow you to post on this repo and will be deleting any further content you post without exception.
